services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: always
    environment:
      - TZ=Europe/Kiev
    mem_limit: 3g
    cpus: 1.5

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: nordiva_admin
      MINIO_ROOT_PASSWORD: nordiva_password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio_data: