services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: always
    environment:
      - TZ=Europe/Kiev
    deploy:  # Will be ignored in Compose, shown just for completeness
      resources:
        limits:
          cpus: '1.5'
          memory: 3g
    mem_limit: 3g
    cpus: 1.5
